### ISSUE TITLE
Downcase on nil in encoder

### ISSUE THREAD

**Issue by klautcomputing** [alexdalitz/dnsruby#123] opened 2017-03-09 20:19 UTC
```
NoMethodError: undefined method `downcase' for nil:NilClass
  .../dnsruby-1.60.0/lib/dnsruby/message/encoder.rb:57:in `put_name'
```

I am seeing `d` being `nil` here https://github.com/alexdalitz/dnsruby/blob/master/lib/dnsruby/message/encoder.rb#L57 I have fixed that with a pretty bad fix locally which just skips the problem, haven't had time to investigate why this is actually happening. Domain in question that I am trying to get DNS for is www.optimumcarcare-caribbean.com

**Comment by keithrbennett** [comment] 2017-03-10 05:27
I'm not familiar with that code, but it looks like it's reasonable for that method to assume that `d` is not `nil`, and the real question is why is `nil` being passed as `d`?

Are there any other clues you could provide?  Could we get a more complete stacktrace?

**Comment by alexdalitz** [comment] 2017-03-10 06:53
Hello - I'm presuming that the problem is related to the record : 

;; ANSWER SECTION (1  record)
www.optimumcarcare-caribbean.com.	21599	IN	CNAME	.

However, using the demo/rubydig.rb code I don't see a problem with this.

Could you please either post the code you are using to generate this, or else the full stack trace?

Thanks!

**Comment by klautcomputing** [comment] 2017-03-10 11:19
Here is the stack trace:
```
../dnsruby-1.60.0/lib/dnsruby/message/encoder.rb:57:in `put_name'
../dnsruby-1.60.0/lib/dnsruby/resource/domain_name.rb:47:in `encode_rdata'
../dnsruby-1.60.0/lib/dnsruby/message/encoder.rb:51:in `block in put_rr'
../dnsruby-1.60.0/lib/dnsruby/message/encoder.rb:29:in `put_length16'
../dnsruby-1.60.0/lib/dnsruby/message/encoder.rb:51:in `put_rr'
../dnsruby-1.60.0/lib/dnsruby/resource/RR.rb:76:in `block in clone'
../dnsruby-1.60.0/lib/dnsruby/message/encoder.rb:6:in `initialize'
../dnsruby-1.60.0/lib/dnsruby/resource/RR.rb:76:in `new'
../dnsruby-1.60.0/lib/dnsruby/resource/RR.rb:76:in `clone'
../dnsruby-1.60.0/lib/dnsruby/resource/RRSet.rb:65:in `add'
../dnsruby-1.60.0/lib/dnsruby/resource/RRSet.rb:19:in `block in initialize'
../dnsruby-1.60.0/lib/dnsruby/resource/RRSet.rb:19:in `each'
../dnsruby-1.60.0/lib/dnsruby/resource/RRSet.rb:19:in `initialize'
../dnsruby-1.60.0/lib/dnsruby/message/section.rb:61:in `new'
../dnsruby-1.60.0/lib/dnsruby/message/section.rb:61:in `block in rrsets'
../dnsruby-1.60.0/lib/dnsruby/message/section.rb:34:in `each'
../dnsruby-1.60.0/lib/dnsruby/message/section.rb:34:in `rrsets'
../dnsruby-1.60.0/lib/dnsruby/cache.rb:140:in `block in get_expiration'
../dnsruby-1.60.0/lib/dnsruby/message/message.rb:345:in `block in each_section'
../dnsruby-1.60.0/lib/dnsruby/message/message.rb:345:in `each'
../dnsruby-1.60.0/lib/dnsruby/message/message.rb:345:in `each_section'
../dnsruby-1.60.0/lib/dnsruby/cache.rb:139:in `get_expiration'
../dnsruby-1.60.0/lib/dnsruby/cache.rb:119:in `message='
../dnsruby-1.60.0/lib/dnsruby/cache.rb:154:in `initialize'
../dnsruby-1.60.0/lib/dnsruby/cache.rb:54:in `new'
../dnsruby-1.60.0/lib/dnsruby/cache.rb:54:in `add'
../dnsruby-1.60.0/lib/dnsruby/packet_sender.rb:54:in `cache_recursive'
../dnsruby-1.60.0/lib/dnsruby/packet_sender.rb:40:in `cache'
../dnsruby-1.60.0/lib/dnsruby/validator_thread.rb:122:in `cache_if_valid'
../dnsruby-1.60.0/lib/dnsruby/validator_thread.rb:64:in `do_validate'
../dnsruby-1.60.0/lib/dnsruby/validator_thread.rb:40:in `run'
../dnsruby-1.60.0/lib/dnsruby/select_thread.rb:757:in `push_to_client'
../dnsruby-1.60.0/lib/dnsruby/select_thread.rb:354:in `block in send_response_to_client'
../dnsruby-1.60.0/lib/dnsruby/select_thread.rb:330:in `each'
../dnsruby-1.60.0/lib/dnsruby/select_thread.rb:330:in `send_response_to_client'
../dnsruby-1.60.0/lib/dnsruby/select_thread.rb:318:in `process_message'
../dnsruby-1.60.0/lib/dnsruby/select_thread.rb:283:in `block in process_ready'
../dnsruby-1.60.0/lib/dnsruby/select_thread.rb:276:in `each'
../dnsruby-1.60.0/lib/dnsruby/select_thread.rb:276:in `process_ready'
../dnsruby-1.60.0/lib/dnsruby/select_thread.rb:221:in `do_select'
../dnsruby-1.60.0/lib/dnsruby/select_thread.rb:70:in `block (2 levels) in initialize'
```
Also I am requesting an 'A' record: `resolved = @resolver.query(domain, 'A')`.

Hope that helps.

**Comment by keithrbennett** [comment] 2017-03-10 13:03
I was able to reproduce this error with the following script:

```
#!/usr/bin/env ruby

require 'dnsruby'
resolver = Dnsruby::Resolver.new
domain = 'www.optimumcarcare-caribbean.com'
response = resolver.query(domain, 'A')
puts response
```

Strangely, when I added a leading space to the domain name, there was no error:

```
;; Answer received from 10.137.0.1 (161 bytes)
;;
;; Security Level : UNCHECKED
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64008
;; flags: qr rd ra cd; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 3

OPT pseudo-record : payloadsize 4096, xrcode 0, version 0, flags 32768


;; QUESTION SECTION (1  record)
;; \032www.optimumcarcare-caribbean.com.	IN	A

;; ANSWER SECTION (1  record)
\032www.optimumcarcare-caribbean.com.	21093	IN	A	38.98.109.40

;; AUTHORITY SECTION (2  records)
optimumcarcare-caribbean.com.	172293	IN	NS	ns20.ixwebhosting.com.
optimumcarcare-caribbean.com.	172293	IN	NS	ns19.ixwebhosting.com.

;; ADDITIONAL SECTION (3  records)
ns19.ixwebhosting.com.	172293	IN	A	69.49.246.19
ns20.ixwebhosting.com.	172293	IN	A	98.130.253.170
```

**Comment by alexdalitz** [comment] 2017-03-10 13:38
Thanks Keith!

I’m flat out on VR just now, but I’ll try to look at this later today / tomorrow morning.

**Comment by alexdalitz** [comment] 2017-03-11 08:28
Interestingly, the script works fine on dnsruby 1.59.3, but fails on 1.60.0 :-(

**Comment by keithrbennett** [comment] 2017-03-11 10:02
Alex, that's great information, I'll try to identify the error using git bisect.

Could you add a tag to the repo for release 1.59.3?

**Comment by keithrbennett** [comment] 2017-03-11 10:30
The code that introduced the error was in commit # bc0f9833f4c156b2f123717ce7deef4a0ddfb61a.

See https://github.com/alexdalitz/dnsruby/blob/master/lib/dnsruby/resource/domain_name.rb#L53-L55

**Comment by alexdalitz** [comment] 2017-03-12 08:13
@keithrbennett thanks so much!

I've now fixed this issue, and updated the dynamic update tests which had caused its introduction.

@klautcomputing Thanks very much for this report, and I'm sorry for the un-forced error :-(  Could you please confirm that this now works for you?

I think I'll make a new dnsruby version once this is confirmed, as there are a few changes it would be worth pushing...

Thanks all!

**Comment by alexdalitz** [comment] 2017-03-14 09:33
Marking this as fixed

**Closed by alexdalitz** 2017-03-14 09:33 UTC

**Comment by klautcomputing** [comment] 2017-03-15 17:15
Just wanted to thank you and let you you know that this fixed it 👍
