### ISSUE TITLE
Using resolver of Dnsruby exposes classes outside of Dnsruby scope

### ISSUE THREAD

**Issue by fuegas** [alexdalitz/dnsruby#175] opened 2021-06-21 08:24 UTC
Hi,

In df7d6d41bd61dd6fa9becf68520c76e5042c9dcb you've added the following line:
```ruby
include Dnsruby
```

However, because this is outside of the Dnsruby module definition, classes (like Message) are exposed on top level now:
```
└─⎇ dependabot/bundler/dnsruby-1-61-6 {14} U:1 ?:1 ✗ ⋗ rails c
Loading development environment (Rails 6.1.3.2)
irb(main):001:0> Message
=> Dnsruby::Message
irb(main):002:0> Cache
=> Dnsruby::Cache
irb(main):003:0> Config
=> Dnsruby::Config
```

This break numerous tests as class names as Cache, Config and Message are not uncommon. In my case I got the following error:
```
TypeError: superclass mismatch for class Message
```

Is it possible to find a way to get `log_and_raise` working without this include?

**Comment by keithrbennett** [comment] 2021-06-21 16:05
@fuegas I agree with you, that's a very reasonable request. I tried commenting out that line, and get this error:

```
TestResolv#test_resolv_address_to_name [/shared/work/dnsruby/test/tc_resolv.rb:57]:
Expected: "dns.google."
  Actual: "dns.google"
```

This looks very familiar but I forget what is the cause. @alexdalitz , do you know?

**Comment by alexdalitz** [comment] 2021-06-22 18:25
OK, I've merged a PR with master which should fix this issue.
I'll release a dnsruby1.61.7 gem now.
Profuse apologies for the inconvenience...
Please let me know if you still have problems with the new version

**Closed** 2021-06-22 18:48 UTC

**Comment by fuegas** [comment] 2021-06-22 19:25
Hi @alexdalitz, no problem, it was found in the pipelines for gem updates and I'm happy you fixed it this fast. Thanks!

I can confirm the pipelines are green again and the new version works as expected for us!
